package eu.fr.indyli.formation.business.entity;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * Alerte generated by hbm2java
 */
@Entity
@Table(name = "Alerte")
public class Alerte extends AbstractEcolisEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4567351989909736794L;
	private Integer idAlerte;
	private Utilisateur utilisateur;
	private String villeDepart;
	private String villeArrivee;
	private Date dateDepot;

	public Alerte() {
		this.dateDepot = new Date();
	}

	public Alerte(Utilisateur utilisateur, String villeDepart, String villeArrivee, Date dateDepot) {
		this.utilisateur = utilisateur;
		this.villeDepart = villeDepart;
		this.villeArrivee = villeArrivee;
		this.dateDepot = dateDepot;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_alerte", unique = true, nullable = false)
	public Integer getIdAlerte() {
		return this.idAlerte;
	}

	public void setIdAlerte(Integer idAlerte) {
		this.idAlerte = idAlerte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utilisateur")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "ville_depart")
	public String getVilleDepart() {
		return this.villeDepart;
	}

	public void setVilleDepart(String villeDepart) {
		this.villeDepart = villeDepart;
	}

	@Column(name = "ville_arrivee")
	public String getVilleArrivee() {
		return this.villeArrivee;
	}

	public void setVilleArrivee(String villeArrivee) {
		this.villeArrivee = villeArrivee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_depot", nullable = false, length = 19)
	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}
	
	public String toString(){
		return ToStringBuilder.reflectionToString(this); 
	}

}
