package eu.fr.indyli.formation.business.entity;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "Comment")
public class Comment implements IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 35991431279109549L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_comment", unique = true, nullable = false)
	private Integer commentId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utilisateur", nullable = false)
	private Utilisateur user;
	
	@Column(name = "corps", length = 65535)
	private String corps;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_creation", nullable = false, length = 19)
	private Date creationDate;

	public Comment() {
	}
 
	public Comment(Utilisateur user, Date creationDate) {
		this.user = user;
		this.creationDate = creationDate;
	}

	public Comment(Utilisateur user, String corps, Date creationDate) {
		this.user = user;
		this.corps = corps;
		this.creationDate = creationDate;
	}
	
	@Override
	public Integer getId() {
		return this.commentId;
	}

	@Override
	public void setId(Integer id) {
		this.commentId = id;
	}

	public Utilisateur getUtilisateur() {
		return this.user;
	}

	public void setUtilisateur(Utilisateur user) {
		this.user = user;
	}

	public String getCorps() {
		return this.corps;
	}

	public void setCorps(String corps) {
		this.corps = corps;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
