package eu.fr.indyli.formation.business.entity;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Announcement generated by hbm2java
 */
@Entity
@Table(name = "Annonce")
public class EcolisAdvertising implements IEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 52399207140791213L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_annonce", unique = true, nullable = false)
	private Integer announcementId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utilisateur", nullable = false)
	private EcolisUser user;
	
	@Column(name = "nature_colis")
	private String parcelContents;
	
	@Column(name = "poids", nullable = false, precision = 10, scale = 0)
	private long poids;
	
	@Column(name = "unite_poids", nullable = false)
	private int unitePoids;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_depot", nullable = false, length = 19)
	private Date depositDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_depart", nullable = false, length = 19)
	private Date startDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_arrivee", nullable = false, length = 19)
	private Date endDate;
	
	@Column(name = "ville_depart", length = 50)
	private String startCity;
	
	@Column(name = "ville_arrivee", length = 50)
	private String endCity;
	
	@Column(name = "prime", nullable = false, precision = 10, scale = 0)
	private long prime;
	
	@Column(name = "devise", nullable = false)
	private int devise;
	
	@Column(name = "statut", length = 10)
	private String statut;
	
	@Column(name = "type_annonce", nullable = false)
	private int announcementType;
	
	@Column(name = "detail", length = 250)
	private String detail;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "announcement")
	private Set<EcolisMessage> ecolisMessages = new HashSet<EcolisMessage>(0);

	public EcolisAdvertising() {
		
	}
	
	
	@Override
	public Integer getId() {
		return this.announcementId;
	}

	@Override
	public void setId(Integer id) {
		this.announcementId = id;
	}

	public EcolisUser getUtilisateur() {
		return this.user;
	}

	public void setUtilisateur(EcolisUser user) {
		this.user = user;
	}

	public String getParcelContents() {
		return this.parcelContents;
	}

	public void setParcelContents(String parcelContents) {
		this.parcelContents = parcelContents;
	}

	public long getPoids() {
		return this.poids;
	}

	public void setPoids(long poids) {
		this.poids = poids;
	}

	public int getUnitePoids() {
		return this.unitePoids;
	}

	public void setUnitePoids(int unitePoids) {
		this.unitePoids = unitePoids;
	}

	public Date getDepositDate() {
		return this.depositDate;
	}

	public void setDepositDate(Date depositDate) {
		this.depositDate = depositDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getStartCity() {
		return this.startCity;
	}

	public void setStartCity(String startCity) {
		this.startCity = startCity;
	}

	public String getEndCity() {
		return this.endCity;
	}

	public void setEndCity(String endCity) {
		this.endCity = endCity;
	}

	public long getPrime() {
		return this.prime;
	}

	public void setPrime(long prime) {
		this.prime = prime;
	}

	public int getDevise() {
		return this.devise;
	}

	public void setDevise(int devise) {
		this.devise = devise;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public int getAnnouncementType() {
		return this.announcementType;
	}

	public void setAnnouncementType(int announcementType) {
		this.announcementType = announcementType;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public Set<EcolisMessage> getMessages() {
		return this.ecolisMessages;
	}

	public void setMessages(Set<EcolisMessage> ecolisMessages) {
		this.ecolisMessages = ecolisMessages;
	}

}
