package eu.fr.indyli.formation.business.entity;
// Generated 25 juin 2017 02:21:10 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "Image")
public class Image extends AbstractEcolisEntity implements  java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6055938211600328115L;
	private Integer idImage;
	private Utilisateur utilisateur;
	private String chemin;
	private Date dateCreation;

	public Image() {
	}

	public Image(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Image(Utilisateur utilisateur, String chemin, Date dateCreation) {
		this.utilisateur = utilisateur;
		this.chemin = chemin;
		this.dateCreation = dateCreation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_image", unique = true, nullable = false)
	public Integer getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Integer idImage) {
		this.idImage = idImage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utilisateur", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "chemin")
	public String getChemin() {
		return this.chemin;
	}

	public void setChemin(String chemin) {
		this.chemin = chemin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_creation", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

}
